### ISSUE TITLE
CTRL+F should focus the Find pane

### ISSUE THREAD

**Issue by jordanbtucker** [AvaloniaUI/AvaloniaEdit#334] opened 2023-05-16 17:28 UTC
When I press <kbd>CTRL</kbd>+<kbd>F</kbd>, the Find pane appears, but I have to click into the text box to begin searching for something. It would be a great quality of life feature to have the Find pane focus automatically.

**Comment by Numpsy** [comment] 2023-06-21 10:53
I've updated an Avalonia app to RC1 and ctrl+f seems to open and focus the search box for me (this is on Windows).
The next and previous buttons on the search panel howoever don't work, though that seems ok with the latest source so it might be caused by https://github.com/AvaloniaUI/AvaloniaEdit/issues/336

**Comment by danipen** [comment] 2023-07-15 11:07
So can we close this issue?

**Closed** 2023-07-15 15:03 UTC
