### ISSUE TITLE
Implement word wrap

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/AvaloniaEdit#74] opened 2019-01-27 19:34 UTC
If I modify the demo app to enable word wrap, text still doesn't wrap to the next line:

        <AvalonEdit:TextEditor Name="Editor"
                               Margin="30"
                               HorizontalScrollBarVisibility="Auto"
                               VerticalScrollBarVisibility="Visible"
                               WordWrap="true"
                               TextBlock.FontSize="30" />

I also tried setting a Width on the control as well and it had no affect on word wrap. Is there something I'm missing here? This is a pretty critical feature for a text editor.

**Comment by garyhertel** [comment] 2019-01-28 00:40
It looks like this might be fixed in the latest 0.7.1-build1248-beta branch if the Horizontal Scroll bar is disabled (should it work with auto?)

**Comment by danwalmsley** [comment] 2019-01-28 17:53
If you have horizontal scrolling then it wont wrap, it scrolls instead.

**Comment by garyhertel** [comment] 2019-01-29 06:35
Thanks, I'll close this issue. I was having trouble getting this to work in 0.7.0, but it does appear to be fixed in the latest verison.

**Comment by garyhertel** [comment] 2019-02-20 06:33
I think I've figured out a little bit about why it's not working for me. With the AvaloniaEdit.Demo, the Syntax Highlighting actually seems to be required to enable it (and even then it's kind of random depending on your text). However, if I comment out this line the wordwrap stops working altogether:

            //_textEditor.SyntaxHighlighting = HighlightingManager.Instance.GetDefinition("C#");

I just want plain text though, with wordwrap and a vertical scrollbar if needed.

Also, looking through the code, I don't actually see anything referencing that WordWrap property (although it does have a comment on setting HorizontalScrollBarVisibility=Disabled, which I did). I'm not really familiar with this codebase though, so I could easily be misunderstanding something.

**Comment by aelij** [comment] 2019-02-20 07:26
@garyhertel I suggest you check how the original AvalonEdit works. If there's a regression, you're welcome to investigate and submit a PR.

**Comment by aelij** [comment] 2019-03-22 11:45
I've checked the implementation again. Word wrapping should not work at all, as it's dependent on the `TextLine` implementation. `TextLine` is a complex API that exists in WPF, and the implementation here is a **very simplified** attempt to copy it, and does not include wrapping capabilities. Once WPF is fully open sourced, I'll try to port the full implementation to Avalonia.

**Comment by garyhertel** [comment] 2019-03-23 00:31
Thanks for looking into this! I tried looking into this myself and quickly got overwhelmed by the complexity of fixing this.

This is still the #1 missing feature for me in Avalonia.

**Comment by Symbai** [comment] 2020-02-09 14:01
@aelij WPF is now open sourced (except of one native dll). Any progress on this?

**Comment by aelij** [comment] 2020-02-10 08:48
Unfortunately it looks like the line services part of WPF [won't be](https://github.com/dotnet/wpf/issues/1936#issuecomment-536644587) open sourced. I will wait and see if some of it will be part of the released WinUI 3.0 code.

**Comment by Gillibald** [comment] 2020-02-16 17:16
Text formatting is soon available via https://github.com/Gillibald/Avalonia/blob/677e683ed64ecb1e67dcecaeba5f10524f0e5f40/src/Avalonia.Visuals/Media/TextFormatting/TextFormatter.cs

**Comment by garyhertel** [comment] 2020-02-16 17:25
Wow! That sounds amazing! Really looking forward to this!

**Comment by Deadpikle** [comment] 2020-05-04 18:24
If it is helpful to anyone, I have word wrapping working (with simple text) on my branch here (runs off latest Avalonia `master`):
https://github.com/Deadpikle/AvaloniaEdit/tree/feature/text-wrapping

Note that multi-line selection does _not_ work when text wraps, nor does the caret drawing on any wrapped line. If things are on one line, things seem to still work OK. Since I'm not using this lib for editing, I'm afraid I don't have the time to get the selection and caret drawing working right now. (Although I'd love to get selection working, frankly...)

_also note that I pretty much just edited things to get things running well enough to work; it's possible I broke some other things along the way and is VERY likely that there are better ways to implement things than how I have it working. This is just a "hey if you aren't editing and just need a temporary wrapping solution in the short term here is a solution"_.

**Comment by igrlas** [comment] 2021-11-15 11:43
hi, so can we use the mentioned text formatters above to implement our own line break or should we wait for native implementation in avaloniaEdit? 
Does anyone know how to make it work with current version?

**Comment by nike4613** [comment] 2021-12-04 23:08
Since `TextFormatter` is available in Avalonia 0.10.10, which this project already uses, is there any chance that it could switch to using it?

**Comment by Deadpikle** [comment] 2021-12-05 14:43
I did some attempts a long, long time ago to get `TextFormatter` working with AvaloniaEdit. It didn't work fully. Selection was broken. But you're welcome to take a look. It would probably need a lot of updating, so not sure it's worth it to start from here or start from scratch. https://github.com/Deadpikle/AvaloniaEdit/tree/feature/text-wrapping

It may be more worth it for someone to look again at `AvalonEdit` and go back to how they do things and see how much better Avalonia's API matches.

**Comment by Gillibald** [comment] 2021-12-06 05:20
The TextFormatter API has improved a lot since then and we are now even closer to WPF's version. Ideally, we take the code directly from https://github.com/icsharpcode/AvalonEdit and fill the missing parts to be more in line with the original repo.

**Comment by nike4613** [comment] 2021-12-06 07:51
@Gillibald 

I began messing with this myself, in https://github.com/nike4613/AvaloniaEdit/commit/8445554c8692fa569e9de17628a5ceec52bf43c6, and there are a few things that are blatantly missing from Avalonia's TextLine implementation:
- `GetTextBounds`
- `TrailingWhitespaceLength`
- `WidthIncludingTrailingWhitespace`

The latter 2 could probably be worked around easily enough, given `GetTextBounds` (or possibly even without) but, as far as I can tell, there isn't really a good way to get around not having `GetTextBounds`.

Other than that, it seems like it would probably be completely usable.

**Comment by Gillibald** [comment] 2021-12-06 11:15
https://github.com/Gillibald/Avalonia/blob/feature/FormattedTextPort/src/Avalonia.Visuals/Media/TextFormatting/TextLine.cs#L136

`GetTextBounds` is trivial to add

**Comment by danipen** [comment] 2022-03-31 13:28
Closed by #67.

**Closed by danipen** 2022-03-31 13:28 UTC
Labels: enhancement
