### ISSUE TITLE
Leak in 0.10.0-preview1

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/AvaloniaEdit#108] opened 2020-08-24 01:29 UTC
There seems to be some sort of leak in AvaloniaEdit 0.10.0-preview1 with Avalonia 0.10.0-preview3 (or also with Avalonia 0.10.0-preview1).

While editing a moderately large document, the memory usage goes up very quickly at every redraw.

To reproduce, open the AvaloniaEdit demo, paste in it some text (e.g. 5 paragraphs of Lorem Ipsum from https://www.lipsum.com/) and then, using the mouse, quickly select and deselect large portions of text. On my machine, after about 10 seconds of this, the memory usage goes up from ~150MB just after starting the program, to over 500MB.

The leak does not seem to happen with AvaloniaEdit 0.9.0-preview1 and Avalonia 0.9.12.

**Comment by arklumpus** [comment] 2020-08-26 02:22
This seems to be due to https://github.com/AvaloniaUI/Avalonia/issues/4557 : the SelectionLayer draws the selection using the DrawingContext.DrawGeometry method. Every time the selected text changes, the shape of the selection geometry also changes, which causes the leak as per that issue.

**Comment by rstm-sf** [comment] 2020-08-26 04:49
Duplicate of #104. It looks like the problem is starting to get better https://github.com/AvaloniaUI/Avalonia/pull/4554

**Comment by HendrikMennen** [comment] 2020-08-29 13:58
I believe @arklumpus is right. Still it is weird after typing about 500chars and 160mb memory leak the difference in elements doesnt look like it has something to do with geometry? (Im using 0.1 preview-4)
![Unbenannt](https://user-images.githubusercontent.com/25281882/91638409-bd538d80-ea0f-11ea-8d1c-4c297d4f53e8.PNG)

**Comment by Gillibald** [comment] 2020-08-29 14:18
I think you found out that AvaloniaEdit is constructing new typefaces over and over again instead of using the cache.

**Comment by Gillibald** [comment] 2020-08-29 14:20
https://github.com/AvaloniaUI/AvaloniaEdit/blob/dbb46ef1e35814b8753a392fefe55925e804e510/src/AvaloniaEdit/Highlighting/HighlightingColorizer.cs#L274

**Comment by HendrikMennen** [comment] 2020-08-29 14:22
https://github.com/AvaloniaUI/AvaloniaEdit/blob/7bb4734611be0323d0929af53aad6a001a112ce2/src/AvaloniaEdit/Text/TextLineRun.cs#L169

Okay I will try to fix it

**Comment by Gillibald** [comment] 2020-08-29 14:24
Simply use this API: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Media/FontManager.cs#L87

**Comment by arklumpus** [comment] 2020-09-01 23:47
Yes, it seems that the issue was twofold: Avalonia 0.10.0-preview4 and #110 are both necessary to prevent the leak

**Comment by aelij** [comment] 2020-09-03 09:05
Fixed in #110

**Closed by aelij** 2020-09-03 09:05 UTC
